version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379

  user-service:
    image: "webdevtoolsandtech/user-service"
    environment:
      - REDIS_ADDRESS=redis:6379
    ports:
      - 80

  currency-calculator:
    build: .
    ports:
      - 3000

  currency-frontend:
    image: "webdevtoolsandtech/currency-frontend"
    ports:
      - 80

  currency-backend:
    image: "webdevtoolsandtech/currency-backend"
    environment:
      - PORT=80
      - REDIS_ADDRESS=redis:6379
      - SESSION_SECRET= "lalala"
      - USER_SERVICE_ADDRESS=user-service:80
      - FRONTEND_ADDRESS=currency-frontend:80
      - CALCULATOR_ADDRESS=currency-calculator:3000
    ports:
      - "80:80"
